## Day-4

## Assignment-4

## Variables

## Strings

In [1]:
# Text Type - String
my_string="Welcome to Day - 4" #assigning string to a variable
print(my_string)
print(my_string.find("Day"))

Welcome to Day - 4
11

## Numeric Type - int,float,complex

In [2]:
a=15.5
b=20
c=10
d=a+b+c

print(int(d))
print(float(d))
print(complex(d))

45
45.5
(45.5+0j)

## Sequence Type - List,Tuple,Range

In [3]:
my_list=[1,2,4,5,["Hello"]]
print(my_list)
print(my_list[4])
print(len(my_list))
print("Let's continue the Tuple in next line")

[1, 2, 4, 5, ['Hello']]
['Hello']
5
Let's continue the Tuple in next line

In [4]:
# Tuple - It can be any Data Type
my_tuple=("hi","hello",[1,2],1,2.5) # Strings must be in quotations
print(my_tuple)

('hi', 'hello', [1, 2], 1, 2.5)

In [5]:
# range() - It prints the Start from start value till stop
x=range(1, 100, 2)
for n in x :
    print(n)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99

## Mapping Type - dictionary

In [6]:
my_dict={
    "Fruit":"Mango",
    "Vegetable":"Tomato",
    "Flower":"Rose"
}
print(my_dict)
print(my_dict["Fruit"])
print(len(my_dict))
print(type(my_dict))

{'Fruit': 'Mango', 'Vegetable': 'Tomato', 'Flower': 'Rose'}
Mango
3
<class 'dict'>

## Set Types - Sets,Forzenset

In [7]:
# Set Types - Sets,Frozen Sets
my_set={"hi","hello",(3,2),"hi"} # In Sets Duplicates will not Allowed
print(my_set)

{'hello', (3, 2), 'hi'}

In [8]:
# Frozenset
nu=(1,2,3,4,5,"hi")
fnum=frozenset(nu)
print("The Forzenset is :" ,fnum)

The Forzenset is : frozenset({1, 2, 3, 4, 5, 'hi'})

## Assigning Values to Variable

In [9]:
Name="Harsha"
Regno=412
GPA=8.6
print(Name)
print(Regno)
print(GPA)

Harsha
412
8.6

## Multiple Assignment

In [10]:
Name,Regno,GPA="Harsha",412,8.6
print(Name)
print(Regno)
print(GPA)

Harsha
412
8.6

## Execise

## 1)Create three variables (a,b,c) to same value of any integer & do the following a) Divide a by 10 b) Multiply b by 50 c) Add c value by 60

In [11]:
a=500
b=25
c=150
print("Division of a by 10 is :",a/10)
print("Multiplying b with is :",b*50)
print("Adding c value by 60 is :",c+60)

Division of a by 10 is : 50.0
Multiplying b with is : 1250
Adding c value by 60 is : 210

## 2)Create a String variable of 5 characters and replace the 3rd character with G

In [17]:
a="E"
b="F"
c="J"
d="H"
e="I"
print(a)
print(b)
print(c.replace("J","G"))
print(d)
print(e)

E
F
G
H
I

## 3)Create two values (a,b) of int,float data type & convert the vise versa, Hint : convert a from int to float datatype & b from float to int datatype

In [13]:
a=10
b=15.5
print(float(a))
print(int(b))

10.0
15